spring:
  application:
    name: inventory-app-service
  cloud:
    config:
      import-check:
        enabled: false
    azure:
      keyvault:
        secret.property-sources[0].endpoint: ${key-vault-endpoint}
  inventory:
    password: ${inventory-app-secret}

server:
  port: 8096
management:
  endpoints:
    web:
      exposure:
        include: health, refresh
