spring:
  application:
    name: inventory-app-service
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: ${key-vault-endpoint}
    config:
      import-check:
        enabled: false


server:
  port: 8096
management:
  endpoints:
    web:
      exposure:
        include: health, refresh
